name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.1  # Change this to match your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email yasinalbayrak@sabanciuniv.edu
          git config --global user.name Yasin
          git checkout --orphan gh-pages
          git rm -rf .
          git add -f build
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
